import { createApp } from 'vue'
import { createPinia } from 'pinia'
import router from './router'
import App from './App.vue'
import '@/style.css'

import {
  create,
  NConfigProvider,
  NMessageProvider,
  NNotificationProvider,
  NDialogProvider,
  NButton,
  NInput,
  NForm,
  NFormItem,
  NLayout,
  NLayoutSider,
  NLayoutContent,
  NLayoutHeader,
  NMenu,
  NSpace,
  NIcon,
  NCard,
  NTable,
  NDataTable,
  NTag,
  NBadge,
  NModal,
  NSelect,
  NUpload,
  NSpin,
  NEmpty,
  NAlert,
  NPopconfirm,
  NDropdown,
  NAvatar,
  NDivider,
  NInputNumber,
  NCheckbox,
  NProgress,
  NStatistic,
  NGrid,
  NGi,
  NScrollbar,
  NTimeline,
  NTimelineItem,
  NLog,
  NCode,
  NTooltip,
  NSwitch,
  NBreadcrumb,
  NBreadcrumbItem,
  NDescriptions,
  NDescriptionsItem,
  NCollapse,
  NCollapseItem,
} from 'naive-ui'

const naive = create({
  components: [
    NConfigProvider,
    NMessageProvider,
    NNotificationProvider,
    NDialogProvider,
    NButton,
    NInput,
    NForm,
    NFormItem,
    NLayout,
    NLayoutSider,
    NLayoutContent,
    NLayoutHeader,
    NMenu,
    NSpace,
    NIcon,
    NCard,
    NTable,
    NDataTable,
    NTag,
    NBadge,
    NModal,
    NSelect,
    NUpload,
    NSpin,
    NEmpty,
    NAlert,
    NPopconfirm,
    NDropdown,
    NAvatar,
    NDivider,
    NInputNumber,
    NCheckbox,
    NProgress,
    NStatistic,
    NGrid,
    NGi,
    NScrollbar,
    NTimeline,
    NTimelineItem,
    NLog,
    NCode,
    NTooltip,
    NSwitch,
    NBreadcrumb,
    NBreadcrumbItem,
    NDescriptions,
    NDescriptionsItem,
    NCollapse,
    NCollapseItem,
  ],
})

const app = createApp(App)
app.use(naive)
app.use(createPinia())
app.use(router)
app.mount('#app')
